### ISSUE TITLE
Rerolling can (and often does) give the same ability again

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [darklordabc/chc2issues#118]
Reroll x marks and bam instantly x marks

**Comment by beepbeepboop** [comment]
Yes! please balance!

Example:
I'm playing lion because I want his finger of death, that's all I care about.
I'll choose all of his other shitty abilties just to increase my chances of getting finger.
Now I have 5 abilties, 3 of those abilties are lions abilities and 2 of them are from Lich, i still want finger of death
I have 2 choices:
1)reroll one of the 3 useless lion abilities to get finger of death (have a 32.5% chance of getting getting finger of death, and a 32.5% change of getting the same ability I just rerolled)
2) reroll one of the 2 very good lich abilities I have and have (65% chance of getting finger of death)


This is such a hard choice to make and I always end up in a situation like this just because of the fact that you can get the same stupid ability back after retraining it away...

**Comment by li0nza** [comment]
I just had a game as OD where I got "essence aura" on the 2nd spell pick. I chose it, and then I got it as a chose on spell pick 2, 3 and 4 too

**Comment by beepbeepboop** [comment]
@li0nza That's slightly different because there's currently 2 OD passives in the game "Essense Aura" and "Essance Flux" and I don't mind getting the same ability more than once on different rolls, because sometimes in your first pick you have to choose between essence aura and arcane orb, and you need both, so you want it to repeat again in your next pick

**Comment by li0nza** [comment]
@beepbeepboop I already picked it. And I got it again. It should be removed from the pool after you pick it. Regardless of how many were actually the aura, because I 100% saw atleast 2 auras after I had already picked one.

**Comment by dym-sh** [comment]
also double-(re)rolling same ability, like twice of zeus ult (on the same hero, from regular leveling)

**Comment by SanctusAnimus** [comment]
Should be fixed
