### ISSUE TITLE
Suggestions for fixing an unfair/uncounterable build

### ISSUE THREAD

**Issue by beepbeepboop** [darklordabc/chc2issues#164]
Rearm is my favourite build and in duels it's not completely uncounterable. But the fact that people can use smoke of deceit during creep waves for the 3 waves that can actually counter OP rearm builds kinda sucks.
There's 2 very broken builds that thankfully aren't perfect:
1) rearm,guardian angel
2) ream,devour

1) gives you infinite tank against all creep waves irrelevant of the level
2) gives you infinite damage against all creep waves irrelevant of the level

If you are playing duos and collectively the 2 players have this build then there's nothing anyone can do to defeat you, because even when losing 100 duels with 100 losers curses on you it doesn't affect your ability to kill creep waves. (Roshan is the only exception but one player can tank while the other player uses guardian angel on them, Then all you need is 1 percentage spell for rosh)

I propose one of the following options to prevent this perfect build from existing:
1) Make it impossible for a duo team to get: rearm, guardian angel and devour at the same time
2.1) take out devour, nobody will miss it
2.2) make devour not affect ancients or creeps over a certain level
3) don't allow guardian angel rearm in duos, only solos where it is balanced because you can get stunned
4) take out smoke of deceit which allows the players to skip the one round that completely counters their build (purge and stun creeps)
5) pray that somehow the rearm rework the devs are working on will fix all of this

I don't like banning abilities because I like having everything being possible, because almost every build does have a counter to it. Except devour. no matter how many losers curses you give someone they can still use devour to defeat creep waves.

**Comment by diegomadness** [comment]
I just played a very fun 2x6 game that lasted 1 hour. Around ~20 wave me and my friend had 50k net worth when enemy Doom and Skywrath had 25k. Next time I paid attention to them they had 75k when we had 68k. 
I wish I could have saved a replay because this was a guide on almost all the Rearm abuses.

Initially, they had **devour+rearm**+multicast on Doom(320 gold per use, 5k net worth per page). Eventually on 160k net worth mark he just bought 2 tomes of exchange and Skywrath started eating creeps.
Then, of course, the fun part arrived.
Rearm+Doom(pierces BKB)
Rearm+Winter's curse(pierces BKB)
Rearm+Sacred Arrow(instakill any creep)
Rearm+Primal Roar(pierces BKB)
Rearm+Death Ward(basically the only thing you want for both duels and waves <60)
They were looking desperately for Rearm+Chrono but failed, so they were just changing one OP ultimate for another.

And of course, since they had around 200k net they had global silence, warlock's golems, untouchable to eat in peace, multicast and bad juju at some point with False Promise to smoke+blademail kill any hard late-game wave. They literally were able to buy any skill in the game.

Man, I even bought a Toxin Spider and a Granite Golem to try something - but they were just eaten first every wave. I have both May and April seasons completed above 2200+ mmr rank, but have 0 ideas about how these kinds of builds can be countered. Mostly because what you need to do with Rearm is to sit in endless Ghost Scepter and cast any OP ultimate. 

I have no problems with rearm itself if we are talking about Macropire or non-Lich-talent Chain frost let's say. But for sake of the good state of the game I suggest the following abilities to be restricted from rearming:

Devour(creep instakill, endless gold, +20-30 min game length)
Sacred Arrow(creep instakill)

RP
Doom
Winter's Curse
Primal Roar
Chrono- all of these are BKB piercing CC, Chrono also is 100% survival on creep rounds

Will-o-wisp 
Death Ward
Guardian Angel - excellent no brain clear and survival options

Supernova
Earth Splitter
Tombstone - not sure if banned already, but also fall in the categories above

Some of these might be banned already, I am grateful that at least Borrowed time can't be rearmed. Otherwise, every time Rearm is in play I expect pretty garbage game experience and abuses.

**Comment by Draze22** [comment]
I take it you play custom hero chaos because in custom hero clash (which this github is for) rearm doesn't work on around 50% of those abilities and tombstone and supernova have been removed from the game.

**Comment by Draze22** [comment]
The original post is now outdated since devour and guardian angel are no longer rearmable.
