### ISSUE TITLE
Seconds of Invulnerability Needed after losing an aegis

### ISSUE THREAD

**Issue by Wintarogar** [darklordabc/chc2issues#290]
After death from creeps, you need at least two seconds of invulnerability; otherwise, after the time runs out, there is a chance to be instantly killed by a roshan or creeps, without even having time to use the perkmet or ability.

**Comment by Draze22** [comment]
This is particularly needed for when players have high ping and can't instantly use defensive abilities or items. Although I would argue only 0.5 to 1 second of invulnerability is needed.

**Comment by fcalife** [comment]
what

**Comment by Draze22** [comment]
Aegises can sometimes be completely uses because creeps can 1 shot you multiple times in a row before you get the chance to use an ability such as shallow grave which has a moderately long cast point. Giving players a small grace period where they take no damage and can't get stunned would stop this from being an issue.

It's definitely not urgent to have this feature implemented but its a nice QoL feature that stops players from sometimes having to spam their abilities after they lose an aegis to stop them from instantly dying again. I would argue this feature is very similar to the QoL/balance feature of giving players a few seconds of time to prepare once they are spawned into a duel.

**Comment by fcalife** [comment]
Implemented
