### ISSUE TITLE
shadowraze f&%cks hotkeys

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [darklordabc/chc2issues#71]
![image](https://user-images.githubusercontent.com/50186248/78885438-f78fb300-7a9f-11ea-8164-248d13b76fbf.png)
![image](https://user-images.githubusercontent.com/50186248/78885448-fe1e2a80-7a9f-11ea-92d6-721563761e24.png)

**Comment by SanctusAnimus** [comment]
secondary **visible** abilities currently moved to the end of the list, due to some abilities manipulations. Think of it as of compromise for reliable work and visibility of all abilities and books. In the end there is like what, 3 abilities that have those unhidden linked abilities (and i still think that True Form gives out bonus spells undeservedly).
We will be able to fix this probably, yet it's not a first priority for now

**Comment by li0nza** [comment]
@AustraliaIsMyCity @SanctusAnimus when you move the 2 other shadow razes they do get assigned to the hotkeys.  I had this issue last night, but it did look like I lost my "R" keybind when doing that

**Comment by beepbeepboop** [comment]
When this gets fixed does it mean that when you playing duos and your friend gives you True Form you'll actually get the bonus ability too?
Really sucked when my friend swapped and gave me true form, It didn't give me the bonus ability linked with it, And then I still had to deal with the known battlefury bug...

**Comment by SanctusAnimus** [comment]
Losing hotkeys should no longer be an issue
